src/Entity/WorkSession.php
<?php

namespace App\Entity;

use App\Repository\WorkSessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: WorkSessionRepository::class)]
class WorkSession
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups('work_session:read')]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Groups('work_session:read')]
    private ?\DateTimeInterface $start = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    #[Groups('work_session:read')]
    private ?\DateTimeInterface $finish = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $employee = null;

    #[ORM\OneToMany(mappedBy: 'workSession', targetEntity: WorkSessionComment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\ManyToMany(targetEntity: Task::class)]
    private Collection $completedTasks;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->completedTasks = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStart(): ?\DateTimeInterface
    {
        return $this->start;
    }

    public function setStart(\DateTimeInterface $start): static
    {
        $this->start = $start;

        return $this;
    }

    public function getFinish(): ?\DateTimeInterface
    {
        return $this->finish;
    }

    public function setFinish(?\DateTimeInterface $finish): static
    {
        $this->finish = $finish;

        return $this;
    }

    public function getEmployee(): ?User
    {
        return $this->employee;
    }

    public function setEmployee(?User $employee): static
    {
        $this->employee = $employee;

        return $this;
    }

    public function getDuration(): ?\DateInterval
    {
        if($this->finish === null) {
            return null;
        }

        return $this->start->diff($this->finish);
    }

    /**
     * @return Collection<int, WorkSessionComment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(WorkSessionComment $workSessionComment): static
    {
        if (!$this->comments->contains($workSessionComment)) {
            $this->comments->add($workSessionComment);
            $workSessionComment->setWorkSession($this);
        }

        return $this;
    }

    public function removeComment(WorkSessionComment $workSessionComment): static
    {
        if ($this->comments->removeElement($workSessionComment)) {
            // set the owning side to null (unless already changed)
            if ($workSessionComment->getWorkSession() === $this) {
                $workSessionComment->setWorkSession(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Task>
     */
    public function getCompletedTasks(): Collection
    {
        return $this->completedTasks;
    }

    public function addCompletedTask(Task $completedTask): static
    {
        if (!$this->completedTasks->contains($completedTask)) {
            $this->completedTasks->add($completedTask);
        }

        return $this;
    }

    public function removeCompletedTask(Task $completedTask): static
    {
        $this->completedTasks->removeElement($completedTask);

        return $this;
    }
}

src/Controller/WorkSessionController.php
<?php

namespace App\Controller;

use App\Entity\WorkSession;
use App\Entity\WorkSessionComment;
use App\Form\WorkSessionCommentType;
use App\Repository\TaskRepository;
use App\Repository\WorkSessionRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/work-sessions')]
class WorkSessionController extends AbstractController
{
    protected EntityManagerInterface $entityManager;
    protected WorkSessionRepository $workSessionRepository;
    protected TaskRepository $taskRepository;
    
    public function __construct(EntityManagerInterface $entityManager, WorkSessionRepository $workSessionRepository, TaskRepository $taskRepository)
    {
        $this->entityManager = $entityManager;
        $this->workSessionRepository = $workSessionRepository;
        $this->taskRepository = $taskRepository;
    }

    #[Route('/start', name: 'app_work_session_start')]
    public function startSession(): Response
    {
        // uniquement les employées peuvent démarrer une session de travail
        if(!$this->isGranted('ROLE_EMPLOYEE')) {
            throw $this->createAccessDeniedException();
        }

        // Regarder si une session de travail est déjà en cours
        $currentSession = $this->workSessionRepository->getCurrentWorkSession($this->getUser());

        // Si déjà une session en cours on redirige vers la session
        if($currentSession !== null) {
            return $this->redirectToRoute('app_work_session_show', ['id' => $currentSession->getId()]);
        }
        
        // Sinon on crée une nouvelle session
        $workSession = new WorkSession;
        $workSession->setEmployee($this->getUser());
        $workSession->setStart(new DateTime);
        $this->entityManager->persist($workSession);
        $this->entityManager->flush();

        // On redirige vers la session
        return $this->redirectToRoute('app_work_session_show', ['id' => $workSession->getId()]);
    }

    #[Route('/finish', name: 'app_work_session_finish')]
    public function finishSession(): Response
    {
        // uniquement les employées peuvent arreter une session de travail
        if(!$this->isGranted('ROLE_EMPLOYEE')) {
            throw $this->createAccessDeniedException();
        }

        // Regarder si une session de travail est en cours
        $currentSession = $this->workSessionRepository->getCurrentWorkSession($this->getUser());
        
        // Si aucune session en cours on fait une erreur
        if($currentSession === null) {
            throw $this->createNotFoundException();
        }
        
        // Sinon on termine la session
        $currentSession->setFinish(new DateTime);
        $this->entityManager->flush();

        // On redirige vers le détail de la session
        return $this->redirectToRoute('app_work_session_show', ['id' => $currentSession->getId()]);
    }

    #[Route('/{id}', name: 'app_work_session_show', requirements: ['id' => '\d+'])]
    public function showSession(WorkSession $workSession, Request $request): Response
    {
        // Si c'est un employee et que la tâche est assigné à quelqu'un d'autre alors on refuse
        if($this->isGranted('ROLE_EMPLOYEE')) {
            if($workSession->getEmployee() !== $this->getUser()) {
                throw $this->createAccessDeniedException();
            }
        }

        $tasks = $this->taskRepository->findUserTasks($this->getUser());
        
        $comment = new WorkSessionComment;
        $form = $this->createForm(WorkSessionCommentType::class, $comment);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {
            $comment->setWorkSession($workSession);
            $comment->setUser($this->getUser());
            $comment->setDate(new DateTime);

            $this->entityManager->persist($comment);
            $this->entityManager->flush();

            return $this->redirectToRoute('app_work_session_show', ['id' => $workSession->getId()]);
        }

        return $this->render('work_session/show.html.twig', [
            'workSession' => $workSession,
            'tasks' => $tasks,
            'form' => $form->createView()
        ]);
    }
}

templates/work_session/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des sessions{% endblock %}

{% block body %}

    <header class="flex items-center justify-between py-4 border-b-2 border-solid border-slate-100 mb-5">
        <h1 class="font-bold text-xl">Liste des sessions</h1>
        
        <div class="flex flex-row gap-5">
            {% if 'ROLE_EMPLOYEE' in app.user.roles %}
                {% if currentSession %}
                    {% include 'components/_button.html.twig' with {
                        'text': 'Voir ma session en cours',
                        'route': path('app_work_session_show', {'id': currentSession.id}),
                        'icon': 'fas fa-eye',
                    } %}
                {% else %}
                    {% include 'components/_button.html.twig' with {
                        'text': 'Démarer une session',
                        'route': path('app_work_session_start'),
                        'icon': 'fas fa-play',
                    } %}
                {% endif %}
            {% endif %}
        </div>
    </header>

    <ul>
        {% for session in workSessions %}
            {% if session.finish is null %}
                <li>Session en cours depuis {{ session.start|date('d/m/Y H:i:s') }} - <a href="{{ path('app_work_session_show', {'id': session.id}) }}">Voir</a></li>
            {% else %}
                <li>Session de {{ session.duration|date("%hh %im %ss") }} le {{ session.start|date('d/m/Y') }} - <a href="{{ path('app_work_session_show', {'id': session.id}) }}">Voir</a></li>
            {% endif %}
        {% endfor %}
    </ul>


{% endblock %}

templates/work_session/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}

    <header class="flex items-center justify-between py-4 border-b-2 border-solid border-slate-100 mb-5">
        <h1 class="font-bold text-2xl">Détail de la session</h1>

        <div class="flex flex-row gap-5">
            {% include 'components/_button.html.twig' with {
                'text': 'Tableau de bord',
                'route': path('app_home'),
                'icon': 'fas fa-home'
            } %}
        </div>
    </header>

    <main class="grid grid-cols-1 gap-3">
        {# Status #}
        <section class="bg-slate-50 rounded-md p-4 row-span-2 shadow-md">
            {% include 'components/_clock.html.twig' with {
                'workSession': workSession,
            } %}

            <div class="text-center">
                {% if workSession.finish is null %}
                    {% include 'components/_button.html.twig' with {
                        'text': 'Terminer la session',
                        'icon': 'fa-solid fa-check',
                        'route': path('app_work_session_finish', {'id': workSession.id})
                    } %}
                {% endif %}
            </div>
        </section>

        {# Tâches #}
        <section class="bg-slate-50 rounded-md p-4 row-span-2 shadow-md"> 
            {% if workSession.finish is null %}
                <section class="grid grid-cols-2 gap-10">
                    <div>
                        <h2 class="text-xl font-bold mt-4 mb-2 sticky top-0 p-2">À faire</h2>
                        <ul class="mt-2">
                            {% for task in tasks|filter(t => workSession.completedTasks.contains(t) == false) %}
                                <li class="mb-2 flex items-center p-2 bg-slate-50 rounded">
                                    <a href="{{ path('app_task_complete', {'id': task.id}) }}"
                                    class="text-xs border-2 border-blue-600 border-solid text-blue-600 hover:bg-blue-600 hover:text-white font-bold p-1 rounded flex items-center">
                                        <i class="fas fa-check"></i>
                                    </a>
                                    <span class="ml-2">{{ task.title }}</span>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div>
                        <h2 class="text-xl font-bold mt-4 mb-2 sticky top-0 p-2">Tâches réalisées</h2>
                        <ul>
                            {% for task in workSession.completedTasks %}
                                <li class="mb-2 flex items-center p-2 bg-slate-50 rounded">
                                    <span class="line-through">{{ task.title }}</span>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </section>
            {% else %}
                <h2 class="text-xl font-bold mt-4 mb-2 sticky top-0 p-2">Tâches réalisées ({{ workSession.completedTasks|length }})</h2>
                <ul>
                    {% for task in workSession.completedTasks %}
                        <li class="mb-2 flex items-center p-2 bg-slate-50 rounded">
                            <span class="line-through">{{ task.title }}</span>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </section>

        {# Commentaires #}
        <section class="bg-slate-50 rounded-md p-4 row-span-2 shadow-md">
            <h2 class="text-xl font-bold mt-4 mb-2">Commentaires ({{ workSession.comments|length }})</h2>
                {% for comment in workSession.comments %}
                    <div class="border p-2 mb-2">
                        <p class="text-xs mb-1">De {{ comment.user.firstname }} le <time>{{ comment.date|date('d/m/Y à H:i') }}</time></p>
                        <p>{{ comment.text }}</p>
                    </div>
                {% endfor %}
            </div>
        
            <h3 class="text-lg font-bold mt-4 mb-2">Ajouter un commentaire</h3>
            <div class="mt-2">
                {{ form_start(form) }}
        
                {{ form_widget(form) }}
        
                {% include 'components/_button.html.twig' with {
                    'text': 'Ajouter',
                    'icon': 'fa-solid fa-plus',
                    'type': 'submit'
                } %}
        
                {{ form_end(form) }}
            </div>
        </section>
    </main>
{% endblock %}